name: Publish Production Container

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag production Docker container
        run: docker-compose up --build -d && docker tag waterstoragecalculator/api-prod ${{ secrets.DOCKERHUB_USERNAME }}/waterstoragecalculator

      - name: Publish production Docker container
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/waterstoragecalculator:latest
